FROM python:3.9-buster
ENV PYTHONUNBUFFERED=1

WORKDIR /src
COPY api api
COPY entrypoint.sh ./

RUN pip3 install --upgrade pip
RUN pip3 install "uvicorn[standard]"
RUN pip3 install --no-cache-dir --upgrade -r /src/api/requirements.txt

ENTRYPOINT ["bash","entrypoint.sh"]
